(load "c++/c++-mode")
(load "js/js-mode")
(load "markdown/markdown-mode")
(load "php/php-mode")
(load "ruby/ruby-mode")

(setq-default linum-format "%5d ")
;(global-hl-line-mode t)
;(hl-line-mode t)
;(highlight-80+-mode t)
